create database DatabaseGroupI;
use DatabaseGroupI;

create table register_city_name(
	id int auto_increment primary key,
    city_name varchar(255),
    city_population int,
    num_family_c int
);

create table register_barangay(
	id int auto_increment primary key,
    barangay_name varchar(255),
    barangay_population int,
    num_family_b int
);

create table register_family_name(
	id int auto_increment primary key,
    family_name varchar(255),
    family_size int,
    num_children int
);

create table register_person(
	id int auto_increment primary key,
    person_fname varchar(255),
    person_sname varchar(255),
    person_age int,
    person_gender bool,
    marital_status varchar(255),
    person_occupation varchar(255)
);

INSERT INTO register_city_name(city_name, city_population, num_family_c)
VALUES
    ('Caloocan', '1583978', ''),
    ('Pasay', '416522', ''),
    ('Quezon', '2936116', ''),
    ('Batangas', '237370', ''),
    ('Cotabato', '179433', ''),
    ('Mandaluyong', '305576', ''),
    ('Pasig', '755300', ''),
    ('Iloilo', '387681', ''),
    ('Taguig', '644473', ''),
    ('Manila', '1780148', ''),
    ('Makati', '510383', ''),
    ('Tagaytay', '71181', ''),
    ('Parañaque', '665822', ''),
    ('Cavite City', '115932', ''),
    ('Cebu', '922611', ''),
    ('Zamboanga', '861799', ''),
    ('Cabanatuan', '220250', ''),
    ('cagayan De Oro', '675950', ''),
    ('Davao', '1632991', ''),
    ('Dagupan', '171271', '')
;

INSERT INTO register_barangay(barangay_name, barangay_population, num_family_b)
VALUES
 		('Brgy. 89', , ),
		('Brgy. 105', , ),
		('Commonwealth', , ),
		('Bukal', , ),
		('Poblacion 1', , ),
		('Addition hills', , ),
		('San antonio', , ),
		('Santa Cruz', , ),
		('Lower Bicutan', , ),
		('Binondo', , ),
		('West Rembo', , ),
		('Neogan', , ),
		('Don Bosco', , ),
		('Hen. M. Trias', , ),
		('Paril', , ),
		('Lanzonesa', , ),
		('Balite', , ),
		('Lapasan', , ),
		('Talomo', , ),
		('Pantal', , ),
		('Vicoria', , ),
		('Pulungbulu', , ),
		('San Roque', , ),
		('Montevista', , ),
		('Molino 5', , ),
		('Caridad', , ),
		('Lualhati', , ),
		('Panala-an', , ),
		('Tanato', , ),
		('Brgy 21', , ),
		('Narra', , ),
		('Baybay', , ),
		('Mabuhay', , ),
		('Sto. Tomas', , ),
		('Antongalon', , ),
		('Banlic', , ),
		('Pula', , ),
		('Buyon', , ),
		('Oro', , ),
		('Victoria Reyes', , ),
		('Galas', , ),
		('Banilad', , ),
		('Escalante', , ),
		('Bulak', , ),
		('Ligaya', , ),
		('Talisay', , ),
		('Guinatan', , ),
		('Dalipuga', , ),
		('Bayan Luma', , ),
		('Francia', , ),
    ('Aguada', , ),
    ('Amas', , ),
    ('Morales', , ),
    ('Arco', , ),
    ('San Lorenzo', , ),
    ('Agus', , ),
    ('Almanza uno', , ),
    ('Sagpon', , ),
    ('Abella', , ),
    ('Adya', , ),
    ('Barra', , ),
    ('Abgao', , ),
    ('Bical', , ),
    ('Baritan', , ),
    ('Kulaman', , ),
    ('Lugam', , ),
    ('Bakilid', , ),
    ('Tampilong', , ),
    ('Parang', , ),
    ('Espinosa', , ),
    ('Mamali', , ),
    ('Tugatog', , ),
    ('Balante', , ),
    ('Buli', , ),
    ('Alpaco', , ),
    ('Cararayan', , ),
    ('Daanghari', , ),
    ('Santa Rita', , ),
    ('Gaas', , ),
    ('Burgos', , ),
    ('Bagakay', , ),
    ('Maligaya', , ),
    ('Dapco', , ),
    ('Mulapula', , ),
    ('Iwahig', , ),
    ('Bago', , ),
    ('Baviera', , ),
    ('Adecor', , ),
    ('Panipuan', , ),
    ('Progreso', , ),
    ('Ibaba', , ),
		('Balogo', , ),
		('Nonoc', , ),
		('Cabalawan', , ),
		('Ubujan', , ),
		('Cale', , ),
		('Suizo', , ),
		('Leonarda', , ),
		('Parada', , ),
		('Raois', , ),
		('Lumbo', , )
;

INSERT INTO register_family_name(family_name, family_size, num_children)
VALUES
		('Santos', 3, 1),
    ('Mondala', 2, 0),
    ('Manlangit', 1, 0),
    ('Diaz', 1, 0),
    ('Aranete', 2, 0),
    ('Lara', 1, 0),
    ('Mendoza', 1, 0),
    ('Faragones', 1, 0),
    ('David', 4, 2),
    ('Molina', 1, 0),
    ('Borja', 3, 1),
    ('Borja', 3, 1),
    ('Reyes', 1, 0),
    ('Balmes', 5, 3),
    ('Corpuz', 4, 2),
    ('Galvez', 1, 0),
    ('Dimajutoc', 1, 0),
    ('Fajardo', 5, 3),
    ('De Luna',4,2),
    ('Perez', 4,2),
    ('Pinpin', , ),
    ('Salazar', , ),
    ('Cruzada', , ),
    ('Garcia', , ),
    ('Lugami', , ),
    ('Ramos', , ),
    ('Magbuhos', , ),
    ('Aycardo', , ),
    ('Sabandal', , ),
    ('Tano', , ),
    ('Millar', , ),
    ('Gines', , ),
    ('Magpantay', , ),
    ('Mojica', , ),
    ('Pineda', , ),
    ('Abrea', , ),
    ('Dimagiba', , ),
    ('Atayde', , ),
    ('Tividad', , ),
    ('Orodio', , ),
    ('Mangurun', , ),
    ('Paglinawan', , ),
    ('Manganti', , ),
    ('Fabricante', , ),
    ('Tabla', , ),
    ('Arquero', , ),
    ('Fordan', , ),
    ('Nunez', , ),
    ('Nofies', , ),
    ('Yap', , ),
    ('Razon', , ),
    ('Aquino', , ),
    ('Abinoja', , ),
    ('Dimayuga', , ),
    ('Chavez', , ),
    ('Cortez', , ),
    ('Arevalo', , ),
    ('Dela Cruz', , ),
    ('Dela Serna', , ),
    ('Donaire', , ),
    ('Martinez', , ),
    ('Ong', , ),
    ('Medina', , ),
    ('Santiago', , ),
    ('Torres', , ),
    ('Bautista', , ),
    ('Santelices', , ),
    ('Suarez', , ),
    ('Maligaya', , ),
    ('Ferrer', , ),
    ('Villanueva', , ),
    ('Vergara', , ),
    ('Dasig', , )
    
    
;
 
INSERT INTO register_person(person_fname, person_sname, person_age, person_gender, marital_status,
person_occupation)
VALUES
('Steven', 'Santos', 46, 'male', 'married', 'payment_specialist' ),
('Belle', 'Santos', 44, 'female', 'married', 'service_coordinator' ),
('Jodalyn', 'Santos' 22, 'female', 'single', 'college_student' ),
('Angel', 'Mondala' 26, 'female', 'married', 'chemical_engineer' ),
('Charles', 'Mondala' 29, 'male', 'married', 'chemical_engineer' ),
('Jefferson', 'Manlangit' 35, 'male', 'single', 'restaurant_manager' ),
('Aubrey', 'Diaz', 25, 'female', 'single', 'accountant' ),
('Michael', 'Aranete', 35, 'male', 'married', 'call_center_agent' ),
('Marthy', 'Aranete', 29, 'female', 'married', 'pharmacist' ),
('Jaycee', 'Lara', 26, 'female', 'married', 'professor' ),
('Sharie', 'Mendoza', 28, 'female', 'single', 'teacher' ),
('Rhobin', 'Faragones', 25, 'male', 'single', 'it_personnel' ),
('Jose', 'David', 35, 'male', 'married', 'barbeque_vendor' ),
('Ailyn', 'David', 36, 'female', 'married', 'barbeque_vendor' ),
('Arzel', 'David', 22, 'female', 'single', 'college_student' ),
('Jean', 'David', 19, 'female', 'single', 'college_student' ),
('Eusebio', 'Molina', 33, 'male', 'single', 'digital_artist' ),
('Yolanda', 'Borja', 54, 'female', 'married', 'vegetable_vendor' ),
('Arvie', 'Borja', 57, 'male', 'married', 'taxi_driver' ),
('Jordan', 'Borja', 34, 'male', 'married', 'it_specialist' ),
('Frances', 'Borja', 31, 'female', 'married', 'call_center_agent' ),
('Ezekiel', 'Borja', 14, 'male', 'single', 'student' ),
('Christyll', 'Reyes', 49, 'female', 'married', 'principal' ),
('Morris', 'Balmes', 45, 'male', 'married', 'bartender' ),
('Karra', 'Balmes' ,39, 'female', 'married', 'promodizer' ),
('Viel', 'Balmes', 17, 'male', 'single', 'student' ),
('Yanah', 'Balmes', 15, 'female', 'single', 'student' ),
('Simon', 'Balmes', 12, 'male', 'single', 'student' ),
('Royette', 'Corpuz', 44, 'male', 'married', 'electrician' ),
('Lovely', 'Corpuz', 41, 'female', 'married', 'tourist_guide' ),
('Ian', 'Corpuz', 21, 'male', 'single', 'college_student' ),
('Iya', 'Corpuz', 14, 'female', 'single', 'student' ),
('Patrick', 'Galvez', 24, 'male', 'single', 'blogger' ),
('Dianne', 'Dimajutoc', 27, 'female', 'single', 'nurse' ),
('Alvin', 'Fajardo', 39, 'male', 'married', 'data_encoder' ),
('Jonna', 'Fajardo', 40, 'female', 'married', 'system_administrator' ),
('Joseph', 'Fajardo', 19, 'male', 'single', 'college_student' ),
('Ara', 'Fajardo', 18, 'female', 'single', 'college_student' ),
('Mae', 'Fajardo', 10, 'female', 'single', 'student' ),



(‘Donald’, ‘De Luna’, 38, ‘male’, ‘married’, ‘programmer’),
(‘Analyn’, ‘De Luna’, 30, ‘female’, ‘married’, ‘secretary’),
(‘Heart’, ‘De Luna’, 14, ‘female’, ‘single’, ‘student’),
(‘Daryll’, ‘De Luna’, 18, ‘male’, ‘single’, ‘student’),
(‘Gerardo’, ‘Perez’, 40, ‘male’, ‘married’, ‘manager’),
(‘Liza’, ‘Perez’, 35, ‘female’, ‘married’, ‘teacher’),
(‘Tomas’, ‘Perez’, 10, ‘male’, ‘single’, ‘student’),
(‘Allen’, ‘Perez’, 17, ‘male’, ‘single’, ‘student’),
(‘Hilario’, ‘Pinpin’, 60, ‘male’, ‘married’, ‘seaman’),
(‘Fe’, ‘Pinpin’, 68, ‘female’, ‘married’, ‘saleslady’),
(‘Dexter’, ‘Pinpin’, 35, ‘male’, ‘married’, ‘seaman’),
(‘Glenn’, ‘Pinpin’, 30, ‘male’, ‘single’, ‘doctor’),
(‘Denver’, ‘Salazar’, 38, ‘male’, ‘married’, ‘technician’),
(‘Daisy’, ‘Salazar’, 57, ‘female’, ‘married’, ‘supervisor’),
(‘Carlo’, ‘Cruzada’, 37, ‘male’, ‘married’, ‘manager’),
(‘Neri’, ‘Cruzada’, 36, ‘female’, ‘married’, ‘technician’),
(‘Edna’, ‘Garcia’, 44, ‘female’, ‘married’, ‘school_principal’),
(‘Ricky’, ‘Garcia’, 49, ‘male’, ‘married’, ‘artist’),
(‘Karl’, ‘Garcia’, 21, ‘male’, ‘single’, ‘student’),
(‘Danilo’, ‘Lugami’, 51, ‘male’, ‘married’, ‘technician’),
(‘Rosalyn’, ‘Lugami’, 46, ‘female’, ‘married’, ‘secretary’),
(‘Fritz’, ‘Lugami’, 21, ‘female’, ‘single’, ‘manager’),
(‘Brent’, ‘Lugami’, 14, ‘female’, ‘single’, ‘student’),
(‘Aladin’, ‘Ramos’, 66, ‘male’, ‘married’, ‘overseas worker’),
(‘Kert, ‘Ramos’, 39, ‘female’, ‘married’, ‘welder’),
(‘Eugene’, ‘Ramos’, 22, ‘male’, ‘single’, ‘student’),
(‘Eugine’, ‘Ramos’, 20, ‘male’, ‘single’, ‘student’),
(‘Rick’, ‘Magbuhos’, 70, ‘male’, ‘married’, ‘driver’),
(‘Yolly’, ‘Magbuhos’, 65, ‘female’, ‘married’, ‘vendor’),
(‘Erick’, ‘Magbuhos’, 15, ‘male’, ‘single’, ‘student’),
(‘Arnold’, ‘Aycardo’, 41, ‘male’, ‘married’, ‘driver’),
(‘Mary_Joy’, ‘Aycardo’, 34, ‘female’, ‘married’, ‘overseas worker’),
(‘Kim’, ‘Aycardo’, 28, ‘female’, ‘single’, ‘nurse’),
(‘Leo’, ‘Sabandal’, 42, ‘male’, ‘married’, ‘welder’),
(‘Melissa’, ‘Sabandal’, 30, ‘female’, ‘married’, ‘waitress’),
(‘Innah, ‘Sabandal’, 20, ‘female’, ‘single’, ‘teacher’),
(‘Ryan’, ‘Tano’, 42, ‘male’, ‘married’, ‘police’),
(‘Ruth’, ‘Tano’, 29, ‘female’, ‘married’, ‘nurse’),
(‘James’, ‘Tano’, 23, ‘male’, ‘single’, ‘student’),
(‘Michael’, ‘Millar’, 22, ‘male’, ‘married’, ‘programmer’),
(‘Laini’, ‘Millar’, 28, ‘female’, ‘married’, ‘architect’),
(‘Chalie’, ‘Millar’, 13, ‘female’, ‘single’, ‘student’),
(‘Larry’, ‘Gines’, 54, ‘male’, ‘married’, ‘school principal’),
(‘Mau’, ‘Gines’, 33, ‘female’, ‘married’, ‘teacher’),
(‘Alexander’, ‘Gines’, 22, ‘male’, ‘single’, ‘student’),
(‘Arthur’, ‘Gines’, 22, ‘male’, ‘single’, ‘student’),
(‘Knight’, ‘Gines’, 15, ‘male’, ‘single’, ‘student’),
(‘Lando’, ‘Magpantay’, 54, ‘male’, ‘married’, ‘manager’),
(‘Lorie’, ‘Magpantay’, 50, ‘female’, ‘married’, ‘doctor’),
(‘Itchel, ‘Magpantay’, 18, ‘female’, ‘single’, ‘student’),
(‘Antonio’, ‘Mojica’, 69, ‘male’, ‘married’, ‘pilot’),
(‘Luz’, ‘Mojica’, 45, ‘female’, ‘married’, ‘teacher’),
(‘Mark’, ‘Pineda’, 22, ‘male’, ‘married’, ‘programmer’),
(‘Christine’, ‘Pineda’, 36, ‘female’, ‘married’, ‘cashier’),
(‘Christian’, ‘Abrea’, 54, ‘male’, ‘married’, ‘engineer’),
(‘Rica’, ‘Abrea’, 45, ‘female’, ‘married’, ‘lawyer’),
(‘Dana’, ‘Abrea’, 23, ‘male’, ‘single’, ‘student’),
(‘Bernard’, ‘Dimagiba’, 54, ‘male’, ‘married’, ‘driver’),
(‘Patchi’, ‘Dimagiba’, 50, ‘female’, ‘married’, ‘teacher’),
(‘Jj’, ‘Dimagiba’, 30, ‘male’, ‘single’, ‘student’),
(‘John’, ‘Atayde’, 30, ‘male’, ‘married’, ‘driver’),
(‘Kimberly’, ‘Atayde’, 30, ‘female’, ‘married’, ‘manicurist’),
(‘Ray’, ‘Atayde’, 11, ‘male’, ‘single’, ‘student’),
(‘Kim’, ‘Tividad’, 54, ‘male’, ‘married’, ‘engineer’),
(‘Kiara’, ‘Tividad’, 33, ‘female’, ‘married’, ‘architect’),
(‘Johna’, ‘Tividad’, 22, ‘female’, ‘single’, ‘nurse’),
(‘Lonard’, ‘Orodio’, 54, ‘male’, ‘married’, ‘delivery boy’),
(‘Hazel’, ‘Orodio’, 34, ‘female’, ‘married’, ‘technician’),
(‘Roxan’, ‘Orodio’, 18, ‘female’, ‘single’, ‘student’),
(‘Sophia’, ‘Paglinawan’, 22, ‘female’, ‘married’, ‘manager’),
(‘Maxwell’, ‘Paglinawan’, 30, ‘male’, ‘married’, ‘engineer’),
(‘Abdul’, ‘Mangurun’, 54, ‘male’, ‘married’, ‘driver’),
(‘Mikaela’, ‘Mangurun’, 40, ‘female’, ‘married’, ‘lawyer’),
(‘James’, ‘Mangurun’, 20, ‘male’, ‘single’, ‘student’),
(‘Sean’, ‘Manganti’, 30, ‘male’, ‘married’, ‘electrician’),
(‘Kianna’, ‘Manganti’, 29, ‘female’, ‘married’, ‘architect’),
(‘Darwin’, ‘Manganti’, 13, ‘male’, ‘single’, ‘student’),
(‘Joven’, ‘Fabricante’, 59, ‘male’, ‘married’, ‘engineer’),
(‘Maricar’, ‘Fabricante’, 45, ‘female’, ‘married’, ‘programmer’),
(‘Maria’, ‘Fabricante’, 14, ‘female’, ‘single’, ‘student’),
(‘Jose’, ‘Tabla’, 45, ‘male’, ‘married’, ‘chef’),
(‘Karla’, ‘Tabla’, 34, ‘female’, ‘married’, ‘manicurist’),
(‘Stephen’, ‘Tabla’, 23, ‘male’, ‘single’, ‘student’),
(‘Kimberly’, ‘Tabla’, 17 , ‘female’, ‘single’, ‘student’),
(‘Mark Stephen’, ‘Arquero’, 30, ‘male’, ‘married’, ‘programmer’),
(‘Joanna’, ‘Arquero’, 27, ‘female’, ‘married’, ‘nurse’),
(‘Niko’, ‘Fordan’, 31, ‘male’, ‘married’, ‘engineer’),
(‘Sheila’, ‘Fordan’, 35, ‘female’, ‘married’, ‘teacher’),
(‘Joshua’, ‘Nunez’, 24, ‘male’, ‘married’, ‘driver’),
(‘Dianne’, ‘Nunez’, 28, ‘female’, ‘married’, ‘vendor’),
(‘Reynaldo’, ‘Nunez’, 11, ‘male’, ‘single’, ‘student’),
(‘Ramon’, ‘Nofies’, 52, ‘male’, ‘married’, ‘electrician’),
(‘Lexi’, ‘Nofies’, 42, ‘female’, ‘married’, ‘engineer’),
(‘Karmen’, ‘Nofies’, 19, ‘female’, ‘single’, ‘student’),
(‘Alyssa’, ‘Yap’, 32, ‘female’, ‘married’, ‘waitress’),
(‘Raymond’, ‘Yap’, 33, ‘male’, ‘married’, ‘carpenter’),
(‘Keann’, ‘Yap’, 12, ‘male’, ‘single’, ‘student’),
(‘Mark’, ‘Razon’, 50, ‘male’, ‘married’, ‘welder’),
(‘Bianca’, ‘Razon’, 56, ‘female’, ‘married’, ‘saleslady’),
(‘Relz’, ‘Razon’, 22, ‘male’, ‘single’, ‘student’),
(‘Bernard’, ‘Aquino’, 58, ‘male’, ‘married’, ‘driver’),
(‘Yhan’, ‘Aquino’, 44, ‘female’, ‘married’, ‘manicurist’),
(‘Ramon’, ‘Aquino’, 23, ‘male’, ‘single’, ‘student’),
(‘Aaron’, ‘Abinoja’, 37, ‘male’, ‘married’, ‘waiter’),
(‘Jolyn’, ‘Abinoja’, 34, ‘female’, ‘married’, ‘nurse’),
(‘Sean’, ‘Abinoja’, 16, ‘male’, ‘single’, ‘student’),
(‘Chalie’, ‘Dimayuga’, 32, ‘female’, ‘married’, ‘bartender’),
(‘Paul’, ‘Dimayuga’, 30, ‘male’, ‘married’, ‘security guard’),
(‘Jopat’, ‘Dimayuga’, 12, ‘male’, ‘single’, ‘student’),
(‘Irvin’, ‘Chavez’, 30, ‘male’, ‘married’, ‘school principal’),
(‘Bianca’, ‘Chavez’, 25, ‘female’, ‘married’, ‘teacher’),
(‘Jhonathan’, ‘Chavez’, 9, ‘male’, ‘married’, ‘student’),
(‘Nhald’, ‘Cortez’, 50, ‘male’, ‘married’, ‘carpenter’),
(‘Merlie’, ‘Cortez’, 43, ‘female’, ‘married’, ‘painter’),
(‘Apyong’, ‘Cortez’, 21, ‘male’, ‘single’, ‘student’),
(‘Miguel’, ‘Arevalo’, 64, ‘male’, ‘married’, ‘waiter’),
(‘Roselyn’, ‘Arevalo’, 54, ‘female’, ‘married’, ‘overseas worker’),
(‘Andrea’, ‘Arevalo’, 26, ‘female’, ‘single’, ‘therapist’),
(‘Albert’, ‘Dela Cruz’, 44, ‘male’, ‘married’, ‘librarian’),
(‘Patricia’, ‘Dela Cruz’, 34, ‘female’, ‘married’, ‘overseas worker’),
(‘Jj’, ‘Dela Cruz’, 20, ‘male’, ‘single’, ‘student’),
(‘Briant’, ‘Dela Serna’, 60, ‘male’, ‘married’, ‘driver’),
(‘Aliana’, ‘Dela Serna’, 56, ‘female’, ‘married’, ‘vendor’),
(‘Lawrence’, ‘Dela Serna’, 30, ‘male’, ‘single’, ‘student’),
(‘Kiel’, ‘Donaire’, 39, ‘male’, ‘married’, ‘security guard’),
(‘Sam’, ‘Donaire’, 40, ‘female’, ‘married’, ‘teacher’),
(‘Melissa’, ‘Donaire’, 22, ‘female’, ‘single’, ‘student’),
(‘Martina’, ‘Martinez’, 60, ‘female’, ‘married’, ‘chef’),
(‘Andrew’, ‘Martinez’, 54, ‘male’, ‘married’, ‘programmer’),
(‘Cherry’, ‘Martinez’, 25, ‘female’, ‘single’, ‘student’),
(‘Paolo’, ‘Ong’, 42, ‘male’, ‘married’, ‘driver’),
(‘Rhenna’, ‘Ong’, 30, ‘female’, ‘married’, ‘teacher’),
(‘Erwin’, ‘Ong’, 11, ‘male’, ‘single’, ‘student’),
(‘Calvin’, ‘Medina’, 54, ‘male’, ‘married’, ‘programmer’),
(‘Liezel’, ‘Medina’, 33, ‘female’, ‘married’, ‘teacher’),
(‘Dominic’, ‘Medina’, 54, ‘male’, ‘single’, ‘student’),
(‘Jerom’, ‘Santiago’, 57, ‘male’, ‘married’, ‘electrician’),
(‘Danica’, ‘Santiago’, 44, ‘female’, ‘married’, ‘cashier’),
(‘Louise’, ‘Santiago’, 18, ‘female’, ‘single’, ‘student’),
(‘John’, ‘Torres’, 24, ‘male’, ‘married’, ‘driver’),
(‘Marian’, ‘Torres’, 29, ‘female’, ‘married’, ‘overseas worker’),
(‘Marie’, ‘Torres’, 5, ‘male’, ‘single’, ‘student’),
(‘Nelson’, ‘Bautista’, 54, ‘male’, ‘married’, ‘technician’),
(‘Anne’, ‘Bautista’, 50, ‘female’, ‘married’, ‘bartender’),
(‘Elaine’, ‘Bautista’, 22, ‘female’, ‘single’, ‘student’),
(‘Emman’, ‘Santelices’, 48, ‘male’, ‘married’, ‘security guard’),
(‘Noelyn’, ‘Santelices’, 39, ‘female’, ‘married’, ‘teacher’),
(‘Marivic’, ‘Santelices’, 17, ‘female’, ‘single’, ‘student’),
(‘Jaime’, ‘Suarez’, 54, ‘male’, ‘married’, ‘reporter’),
(‘Franchine’, ‘Suarez’, 54, ‘female’, ‘married’, ‘vendor’),
(‘Mae’, ‘Suarez’, 23, ‘female’, ‘single’, ‘student’),
(‘Nick’, ‘Maligaya’, 43, ‘male’, ‘married’, ‘welder’),
(‘Beyonce’, ‘Maligaya’, 36, ‘female’, ‘married’, ‘vendor’),
(‘Dana’, ‘Maligaya’, 22, ‘female’, ‘single’, ‘student’),
(‘Earl’, ‘Ferrer’, 62, ‘male’, ‘married’, ‘pilot’),
(‘Trixie’, ‘Ferrer’, 54, ‘female’, ‘married’, ‘manicurist’),
(‘Angel’, ‘Ferrer’, 26, ‘female’, ‘single’, ‘student’),
(‘Atkins’, ‘Villanueva’, 38, ‘male’, ‘married’, ‘teacher’),
(‘Princess’, ‘Villanueva’, 35, ‘female’, ‘married’, ‘nurse’),
(‘Joyce’, ‘Villanueva’, 19, ‘female’, ‘single’, ‘student’),
(‘Joseph’, ‘Vergara’, 43, ‘male’, ‘married’, ‘carpenter’),
(‘Joy’, ‘Vergara’, 40, ‘female’, ‘married’, ‘architect’),
(‘Yasmine’, ‘Vergara’, 26, ‘female’, ‘single’, ‘student’),
(‘Gabriel’, ‘Dasig’, 44, ‘male’, ‘married’, ‘reporter’),
(‘Jasmine’, ‘Dasig’, 44, ‘female’, ‘married’, ‘musician’),
(‘Catherine’, ‘Dasig’, 23, ‘female’, ‘single’, ‘student’)
;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
